### PR TITLE
Setup circle ci https://circleci.com/docs/2.0/language-elixir/

### PR DESCRIPTION
**Pull request by rohanpujaris**
https://github.com/gothinkster/elixir-phoenix-realworld-example-app/issues/12

### CODE REVIEW

**Comment by rohanpujaris** [comment]
@lbighetti We would have to make one dummy commit once we have added this project to circle ci to test it with this branch. Is this project added to circle ci?

To be sure I merged this branch to the master in the forked repo. All specs passed https://circleci.com/gh/rohanpujaris/elixir-phoenix-realworld-example-app/2

^ If above circle ci passing link is good enough for this to be merged, we can merge directly as well wothout adding the dummy commit. But please add this project to circle ci first if not already added.

**Comment by lbighetti** [comment]
Alright, looks good @rohanpujaris !
I've just set it up the project there!

I'll merge this in and we see if it goes through!

**Comment by lbighetti** [comment]
Worked, awesome!

https://circleci.com/gh/gothinkster/elixir-phoenix-realworld-example-app

**Comment by lbighetti** [comment]
Thanks a lot for the contribution @rohanpujaris ! 👍

**Comment by lbighetti** [comment]
Will do :)

**Pull request merged**
